### ISSUE TITLE
errou a classe Soma

### ISSUE THREAD

**Issue by LucasEmanoel** [LucasEmanoel/topicos#6]
**Describe the bug**

vc fez soma de 2 numeros era de vetor kkkkk

**To Reproduce**
1. Go to Principal/Soma
2. edita o  code
3. save
4. commit 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexsanderthorne** [comment]
pdc
